### ISSUE TITLE
Cannot install abapGit eclipse plugin - PKIX path building failed

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/ADT_Frontend#160]
I try to install the abapGit eclipse plugin from https://eclipse.abapgit.org/updatesite/ and get this error. 

![image](https://user-images.githubusercontent.com/17437789/69215317-ad964700-0b69-11ea-8ec2-552dc6ba6289.png)

Unable to read repository at http://eclipse.abapgit.org/updatesite/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

![image](https://user-images.githubusercontent.com/17437789/69215420-f5b56980-0b69-11ea-9263-63d1e92d4c20.png)

**Comment by larshp** [comment]
hmm, sounds like some certificate problems

try again, I've removed the force HTTPS option

**Comment by christianguenter2** [comment]
Works now with HTTP. Thx.
