### ISSUE TITLE
Java Error: Cannot invoke "org.eclipse.jface.resource.ImageDescriptor.createImage()"

### ISSUE THREAD

**Issue by justrockstar** [abapGit/ADT_Frontend#165]
Hello abapGIT guys,

I want to follow the following tutorial, to save my ABAP code from the Cloud trial version.
https://developers.sap.com/tutorials/abap-environment-abapgit-transfer.html

I installed the ADT_Frontend Plugin (1.1.1) and got the following error:
Cannot invoke "org.eclipse.jface.resource.ImageDescriptor.createImage()" because the return value of "org.eclipse.ui.plugin.AbstractUIPlugin.imageDescriptorFromPlugin(String, String)" is null

![grafik](https://user-images.githubusercontent.com/59475370/71724786-d892dc80-2e31-11ea-9e9f-9631ae71e468.png)

I changed JRE (sapmachine) from 11 to 13, but no change.
I use Eclipse Platform Version: 2019-09 (4.13) Build id: I20190916-1045

Thanks,
Justrockstar

**Comment by abinbaby-sap** [comment]
Hi Justrockstar,

Looks like these exceptions are coming because of some missing icons from some dependent plugins.  Will provide the fix for it soon. 

For the time being you can close the error popup and proceed. This should not affect any functionalities of the plugin.

Cheers Abin.

**Comment by abinbaby-sap** [comment]
Hi Justrockstar,

The issue has been fixed with the pull request #166 and a new plugin version is created v1.1.2 with the fix. Could you please try again. 

Cheers Abin

**Comment by justrockstar** [comment]
Thanks work now. Like you said, closing the error message worked also fine.
