### ISSUE TITLE
Provide an option to remember the credentials, at least the user name

### ISSUE THREAD

**Issue by DerGuteWolf** [abapGit/ADT_Frontend#168]
Having to type in the credential for each single action is quite cumbersome and also from securitty aspects side not the best solution.
There is a secure storage in Eclipse available and the git plugin has also a solution IMHO including other authentication methods besides password.

**Comment by shubhamWaghmare-sap** [comment]
We are currently working on providing the support to store the credentials in Eclipse secure storage.
It will be available in future versions.
