### ISSUE TITLE
update site

### ISSUE THREAD

**Issue by larshp** [abapGit/ADT_Frontend#2]
eclipse update site

Suggest using URL http://eclipse.abapgit.org

is it a good or bad idea to have 1 or 2 repositories for this? one for the raw code and one for the update site?

SAP NetWeaver How-To Guide: SDK for the ABAP Development Tools:
https://www.sap.com/documents/2013/04/12289ce1-527c-0010-82c7-eda71af511fa.html

**Comment by larshp** [comment]
Dependencies:
https://help.eclipse.org/photon/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Fguide%2Ftools%2Feditors%2Fmanifest_editor%2Fdependencies.htm

**Comment by larshp** [comment]
Suggesting having a different repository for the update site, to make sure the size of the work repo does not increase too much, see:
https://github.com/andau/abapCI/blob/master/com.abapci.updateSite/site.xml
https://github.com/andau/abapCI/tree/master/com.abapci.updateSite/features

**Comment by larshp** [comment]
@OleksiiMalikov will try to find someone that can help setting up Maven and Tycho build

Idea is then to have it run automatically on Travis-CI for each merge/commit to master.

When a [tag is created](https://docs.travis-ci.com/user/deployment#conditional-releases-with-on), it will trigger the release process on Travis-CI which will deploy the site to https://github.com/abapGit/eclipse.abapgit.org. And users can then update the Eclipse frontend via update site http://eclipse.abapgit.org

**Comment by absap** [comment]
preparations are already done with PR #40 
Next step would be adding it via GH pages.
