### ISSUE TITLE
HTTP 401, unauthorized

### ISSUE THREAD

**Issue by SharmansShiva** [abapGit/ADT_Frontend#216]
![Capturegit](https://user-images.githubusercontent.com/89929762/133684575-3b82fee3-c3d0-49a1-8148-384654ff04fd.PNG)

**Comment by larshp** [comment]
check your credentials

see https://github.com/abapGit/abapGit/issues?q=is%3Aissue+401+is%3Aclosed

**Comment by SharmansShiva** [comment]
Please advise where to check my credentials ? in SAP or github? I am new using GitHub ,..
