### ISSUE TITLE
Local Codacy Code Checks

### ISSUE THREAD

**Issue by absap** [abapGit/ADT_Frontend#24]
> Both PMD and CheckStyle are already integrated with Codacy, which means you can start using them right now.
> 
> Using Codacy means you’ll get all of these analyses done for you automatically every time you do a commit, plus a list of issues that are expansible to reveal additional detail on the particular problem and how to solve it.

https://blog.codacy.com/review-of-java-static-analysis-tools-5ad86cfc8ae2

There are 2 eclipse plugins available via marketplace:

- https://pmd.github.io/latest/pmd_userdocs_tools.html#eclipse
- https://marketplace.eclipse.org/content/checkstyle-plug

With these plugins, it should be possible to test the source code locally and don't have to wait for the response of codacy on an open PR.

**Comment by larshp** [comment]
suggest adding to the "Development Setup Guide", see https://github.com/abapGit/ADT_Frontend/issues/11

**Comment by larshp** [comment]
I cannot find a way to download it as a configuration file, suggest just adding the default PMD ruleset files

**Comment by absap** [comment]
some checks also came with #52

**Comment by larshp** [comment]
can this be closed?

**Comment by absap** [comment]
spotbugs is used and can be run locally
