### ISSUE TITLE
travis CI

### ISSUE THREAD

**Issue by larshp** [abapGit/ADT_Frontend#50]
I tried setting up travis CI, currently it fails, see
https://travis-ci.org/larshp/ADT_Frontend
Is the full build currently broken, or did I do something wrong?

**Comment by absap** [comment]
I replaced findbugs with spotbugs with PR #53 and set the options `failOnError` & `failOnViolation` to `false`
```xml
<failOnError>false</failOnError>
<failOnViolation>false</failOnViolation>
```
I think this should be fine for now.

If you fetch the new sources and run your travis build again, it should work.

**Comment by larshp** [comment]
It works now, will set it up in a bit

I guess the following finding still needs to be fixed?

`[INFO] Using pointer equality to compare a com.sap.adt.transport.ui.wizard.IAdtTransportSelectionWizardPage with a org.eclipse.jface.wizard.WizardPage in org.abapgit.adt.ui.wizards.AbapGitWizard$PageChangeListener.handlePageChanging(PageChangingEvent) [org.abapgit.adt.ui.wizards.AbapGitWizard$PageChangeListener] At AbapGitWizard.java:[line 118] EC_UNRELATED_TYPES_USING_POINTER_EQUALITY`

**Comment by absap** [comment]
As far as I know is this bug a false positive.
But maybe @sratz can tell you a bit more about it.

I also prepared everything, that we can easily build a new release version of the plugin

**Comment by sratz** [comment]
org.eclipse.jface.dialogs.PageChangingEvent just deals with Object references and the hierarchy of IWizardPage / IDialogPage / WizardPage / DialogPage is a bit awkward to use.

I improved the coding to avoid all of the type casts, see #55.
