### ISSUE TITLE
HTML reuse

### ISSUE THREAD

**Issue by larshp** [abapGit/ADT_Frontend#65]
Okay, so ZABAPGIT uses HTML to render all frontend, can this be reused in Eclipse, and this a good or bad idea?

It will probably not have the Eclipse look'n'feel to it, but there would be no double work when implementing some of the frontend.

**Comment by flaiker** [comment]
I'd say a native look would be more desirable.
Otherwise you lose support for theming / accessibility features / hotkeys / display scaling and so on.
