### ISSUE TITLE
Pull process/popups

### ISSUE THREAD

**Issue by larshp** [abapGit/ADT_Frontend#7]
In abapGit for SAP GUI, the pull happens in ZCL_ABAPGIT_SERVICES_REPO=>GUI_DESERIALIZE.
Note that if a password is needed, this is entered by the user previous to the pull, as it is needed for calculating the status, which checks if a pull is possible or not.
Some of the objects types also have popups, this should be fixed in each serialization class.

**Overwrite popup**
Shown in case an object is modified locally after last pull
![image](https://user-images.githubusercontent.com/5888506/43042982-8f7048d4-8d89-11e8-8203-d9554a8be18a.png)

**Package overwrite popup**
If an object with identical name exists in an unexpected package
![image](https://user-images.githubusercontent.com/5888506/43042986-aacdd10a-8d89-11e8-8e6b-476e16d640ca.png)

**Unmet requirements popup**
![image](https://user-images.githubusercontent.com/5888506/43043009-f13a521c-8d89-11e8-8693-1b935d8b656e.png)

![image](https://user-images.githubusercontent.com/5888506/43043010-f67b3296-8d89-11e8-99f4-23b8b433f440.png)

**Transport required popup**
![image](https://user-images.githubusercontent.com/5888506/43043012-ffcb2bbc-8d89-11e8-8c19-f124eda5e2a7.png)

**Comment by absap** [comment]
Introduced a warning popup "local content will be overwritten" with PR #139

**Comment by larshp** [comment]
okay for now, closing
