### ISSUE TITLE
Required .git suffix at the end of the git repo url

### ISSUE THREAD

**Issue by manuack** [abapGit/ADT_Frontend#74]
Hello,

We tried to use a AWS CodeCommit repo url without the .git suffix at the end, but we were not able to use that.

As far as I know the .git suffix at the end of the git repo url is just convention to indicate that the directory in question is a bare git repository. But I think it is not required.

From my perspective the .git suffix should not be required.

What do you think?

Regards,
Manuel

**Comment by larshp** [comment]
in "normal" abapGit, urls without .git works, havent tried in ADT_Frontend
