### ISSUE TITLE
Error when cloning XSLT

### ISSUE THREAD

**Issue by larshp** [abapGit/ADT_Frontend#79]
When cloing https://github.com/abapGit-tests/XSLT.git

Get errror message "error from cl_o2_api_xsltdesc=>create_new_from_string"

**Comment by absap** [comment]
Import with version 0.13.2 was successful.

<img width="942" alt="Bildschirmfoto 2019-08-27 um 08 15 38" src="https://user-images.githubusercontent.com/41117972/63745659-0aec6600-c8a3-11e9-9a79-c26634136b1c.png">

Hence closing this issue.
