### ISSUE TITLE
Object log after Pull/Clone action

### ISSUE THREAD

**Issue by OleksiiMalikov** [abapGit/ADT_Frontend#97]
Hi,

We thought about some kind of log screen with object status after the import. 
Following details should be included:
- Object Type
- Object Name
- Object Package
- Which objects were imported successfully
- Were there any errors / warnings?
- Error / warning details
- Filter, to search for warnings / errors

![screenshot_2018-12-13_at_17 11 42](https://user-images.githubusercontent.com/41151563/51306549-e5aa9600-1a3d-11e9-9133-3fdbb6c3f632.png)

**Comment by larshp** [comment]
As mentioned before Christmas, this design does not follow how the abapGit backend works

**Comment by larshp** [comment]
The abapGit API, https://docs.abapgit.org/development/api.html does not return any information from `deserialize()`, a prerequsite for this is https://github.com/larshp/abapGit/issues/2169, which describes "aving DESERIALIZE return an instance of ZCL_ABAPGIT_LOG"

I.e. Object Type + Object Name + Object package will not be available. Plus the SAP standard function module(DD_MASS_ACT_C3) used for activating does not return type + name.

When using abapGit in SAP GUI, the user can tell if the import was successful by looking at the status/diff, note that this overview is also very helpful when pushing code.

Suggest implementing a generic error log viewer, which displays the details returned by a ZCL_ABAPGIT_LOG instance.

**Comment by absap** [comment]
see https://github.com/larshp/abapGit/issues/2514
